### ISSUE TITLE
Help compiling for Android

### ISSUE THREAD

**Issue by zymbiosis** [PantryParty/pantry_party#129]
Hello, I am new to nativescript but not new to programming.  I run the android app and was hoping to make some enhancements to the scanning process but I'm unable to get the android app to run from code.  First, I was getting compilation errors, but was able to fix that by changing the sass-loader version down to ~10.1.1 (looks to be a known issue) and having to set the environment variable `--openssl-legacy-provider`.  After doing that, I was able to get it to compile but when trying to run it I got a black screen with red text:

```
record.factory is not a function

TypeError: record.factory is not a function
    at R3Injector.hydrate (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:55044:35)
    at R3Injector.get (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:54865:33)
    at file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:54902:55
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:54902:31)
    at new NgModuleRef$1 (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:68932:26)
    at NgModuleFactory$1.create (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:68986:16)
    at file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:72779:45
    at ZoneDelegate.push.../node_modules/@nativescript/zone-js/zone-nativescript.js.ZoneDelegate.invoke (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:145611:26)
    at Object.onInvoke (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:72187:33)
    at ZoneDelegate.push.../node_modules/@nativescript/zone-js/zone-nativescript.js.ZoneDelegate.invoke (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:145610:32)
    at Zone.push.../node_modules/@nativescript/zone-js/zone-nativescript.js.Zone.run (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:145361:43)
    at NgZone.run (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:72070:28)
    at PlatformRef.bootstrapModuleFactory (file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:72777:23)
    at file:///data/user/0/org.nativescript.PantryParty/files/app/vendor.js:72829:41

```

Seems as if there's a version conflict that I can't seem to track down.  Hoping for some help getting it running so I can start to contribute.  Thank you!

**Comment by zymbiosis** [comment]
I was able to get it running by modifying the following versions:

```
    "sass-loader": "~10.1.1",

    "@nativescript-community/ui-material-bottomsheet": "~5.1.16",
    "@nativescript-community/ui-material-button": "~5.1.16",
    "@nativescript-community/ui-material-ripple": "~5.1.16",
```

I will put in a pull request shortly for this fix.
